### ISSUE TITLE
Stripe API key is Not defined

### ISSUE THREAD

**Issue by rakeshhotker** [shubham1710/MERN-E-Commerce#2]
I tried to clone the repository and tried running it but couldn't as i was getting an error saying stripe api key isn't defined in config, could you tell a fix for that.

**Comment by shubham1710** [comment]
We need to make a config folder and then make a file named deafult.json inside that folder. 
Isnide that we will put our Database URI, JWT Secret Key and Stripe API secret key.

This file is not present on github repo as it is confidential. I will add a sample file though today.
